import app.routes.shoe
import app.routes.home
import app.routes.login
import app.routes.register
import app.routes.flower
import app.routes.fruit
import app.routes.vegetable
import app.routes.admin
import app.routes.fruit_product_1
import app.routes.fruit_product_2
import app.routes.stripe