import app.routes.shoe
import app.routes.home
import app.routes.login
import app.routes.register
import app.routes.gallery
import app.routes.product
import app.routes.flower
import app.routes.fruit
import app.routes.vegetable
import app.routes.admin
import app.routes.cart
import app.routes.stripe
