-- DATABASE_NAME.TABLE_NAME
-- WE ARE CREATING A TABLE CALLED SHOW:
CREATE TABLE IF NOT EXISTS app.SHOE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    -- DOUBLE HAS EIGHT BITS FOR PRECISION WHERE AS
    -- FLOAT HAS FOUR BITS AND WE DO NOT REQUIRE
    -- THE EXTRA PRECISION.
    SIZE FLOAT NOT NULL,
    BRAND VARCHAR(255) NOT NULL

);