"""create the db

Revision ID: 8471e3668c45
Revises: 
Create Date: 2021-02-12 20:20:47.213852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8471e3668c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=89), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoe_brand'), 'shoe', ['brand'], unique=False)
    op.create_index(op.f('ix_shoe_model'), 'shoe', ['model'], unique=True)
    op.create_index(op.f('ix_shoe_size'), 'shoe', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoe_size'), table_name='shoe')
    op.drop_index(op.f('ix_shoe_model'), table_name='shoe')
    op.drop_index(op.f('ix_shoe_brand'), table_name='shoe')
    op.drop_table('shoe')
    # ### end Alembic commands ###
