# where we store the information for the seed page discriptions
seed_info = {
    "Strawberry" : '''Fresca strawberry seeds are so tiny it's hard to believe that these miniature seeds produce big, 
                    mouthwatering traditional strawberries. Start the seeds indoors during the winter and place the seedlings out after the last frost. 
                    While they may not produce much fruit the first year, these sprawling plants will eventually yield heavily over a long season. 
                    They are considered everbearing, and will flower over and over if plants are kept picked. This strawberry is ideal for containers, raised beds, or hanging baskets. 
                    For fruits the first year, give them a really early start in December or January. Grow the seedlings on under bright artificial lights.''',
    "Apple": ''' At maturity, these novel heirloom cucumbers resemble Granny Smith apples with their pale green skins. The skin is tender and thin with fine white spines, 
                and the fruit has a mild flavour. These cucumbers are at their peak at about 8cm (3") in diameter. Crystal Apple cucumber seeds were developed in New Zealand in the 1930s. 
                The plants are very prolific, producing a surprising number of tasty little cucumbers. Maintain regular moisture throughout the growing season and keep vines picked to encourage new fruit formation. 
                Crystal Apple will perform well in containers or raised beds. Choose a three to five gallon container or larger, with good drainage.''',
    "Cherry": '''Mazzard Cherry is a robust and determined cherry tree that offers high yields of tiny, delicious cherries! This wild-ish variety is extremely disease resistant and works great as a root stock for grafting other varieties.
                Mazzard is productive but also incredibly beautiful! In Springtime, the entire tree is engulfed by tiny, off-white cherry blossoms that give even Spring magnolias a run for their money! 
                Fruit presents about 80 days after flowering. This is a great food and habitat shrub, ideal for permaculture design.  ''',
    "Orange": ''' Mandarin trees grow easily from seed, but a seed-grown tree can take several years to be large and mature enough to produce fruit so you have to be a patient person! While not every type of mandarin comes true from seed 
                (that is has fruit that's the same as the parent) the Emperor variety does come true and crops relatively quickly. Most citrus, including mandarins, are grafted or budded onto disease-resistant two-year-old rootstock. 
                Grafted plants should fruit within two years of purchase. ''',
    "Pear": ''' Asian Pears are DELICIOUS, but you know, I didn't really care for them until our trees (reluctantly planted) started producing. Now they are some the most productive trees in our orchard and the fruit we wait for the most. 
                If you haven't tried an Asian Pear before, they are quite different from European varieties. They are crisp, juicy, flowery and sweet. There is just no comparison. If you have tried ones from the grocery store, you'll note that they are only shadow of what I have just described. Gotta be home grown!  ''',
    "Banana": ''' Musa sikkimensis is one of around 50 species of banana in the genus ‘Musa’.
                    It is also known by the more common name – Darjeeling.
                    Native to the Himalayas it is one of the highest altitude bananas.
                    It grows to around 4 meters in height as well as producing huge green and red tinged leaves. ''',
    "Carrot": ''' Canada Carrot Seeds is a generously sized early season Chantenay carrot with broad shoulders, blunt tips, and strong, tall tops. Perfect for both long term storage and fresh eating. 
                Your kids will love pulling Canada carrots up by their strong tops, rinsing them under the hose, and crunching them right there in the organic vegetable garden. Plan for a summer crop, and a second harvest in the fall for winter storage. 
                Learn when to plant carrot seeds in our How to Grow Carrots instructions in the tab below. Spacing carrot seeds is very important - learn how to avoid thinning carrot seedlings. ''',
    "Tomato": ''' Manitoba Tomato seeds produce vigorous determinate plants that thrive in cool climates with short seasons. An early producer with excellent yields, Manitoba Heirloom tomatoes were originally developed in the mid 1950's by the Morden Experimental Farm in Morden, MB to ripen during the short summer season. 
                An excellent choice on the West Coast.
                A prairie favourite, Manitoba tomato plants bear medium-large fruits 170 grams (6 oz.). The bright red fruits have smooth skin and firm, meaty flesh with a refreshing, tangy tomato taste. Well suited for slicing and preserving.
                Manitoba tomato seed plants are resistant to, or tolerant of, the following tomato diseases: Fusarium Wilt and Verticillium Wilt. ''',
    "Cucumber": ''' Ishtar can be field grown, but it performs best in a greenhouse from spring to autumn. It was very productive for us in raised beds. Ishtar is a smooth-skinned, parthenocarpic, Beit Alpha type, so it does not require pollination to produce its seedless fruits. 
                If pollination occurs (if it is not isolated, or if it's grown outdoors), seeds may develop. 
                The plants are vigorous and strong, with 13-14cm (5-5½”) long, cylindrical fruits. This variety also boasts intermediate resistance to Powdery Mildew, so it’s great for coastal growers who seem to experience this cucumber disease every summer. ''',
    "Spinach": ''' A speedy new hybrid for baby-leaf spinach production or full-size growing. The flavour is simple, but pronounced, and excellent for raw salad eating. Yukon spinach seeds grow so fast that it's a good option for filling in between other main season crops. 
                Try it for fall and early winter harvests under low tunnel protection. Yukon has high resistance to Downy Mildew races 1-12, 14, and 15, with intermediate resistance to race 13. Spinach does best in cool weather. Direct sow March 1 to April 15. 
                For late spring and early summer plantings use Tyee, and for quick harvest use Space and Olympia. Spinach will bolt once days get long and hot. Some varieties grow enough to harvest before they bolt. For continuous supply, plant every 3 weeks. ''',
    "Lettuce": ''' Lettuce Leaf basil seeds produce very large, bright, puckered green leaves with a glorious aroma. Provide high soil fertility and a light, well-dug soil to get the largest leaves. We recommend using potting soil with two tablespoons of Gaia All Purpose 4-4-4 per liter of soil. 
                Try this mix in containers in your patio herb garden. Tear the big leaves into salad mixes or use whole leaves to wrap savory morsels like brochettes or salad rolls. Lettuce Leaf Basil is a sweet basil, with milder flavour than the Genovese types. 
                It's perfect for the home gardener, but it also makes an eye catching and unique bundle for the market table. ''',
    "Broccoli": ''' Small beads on large, smooth heads with very tightly packed beads and very few side shoots. This remarkably versatile broccoli can be grown year round in cool coastal regions. If you haven't had much luck with broccoli before, try Centennial broccoli seeds. 
                Expect to harvest around three and a half months after transplanting, no matter when you start. So it's a good variety for planting every three or four weeks from spring to late summer. Centennial has a lovely, rich broccoli flavour that is a little sweeter after frost. 
                This is a superb broccoli for CSA programs, as it will produce pretty much all season. ''',
    "Rose": ''' Tropaeolum minus. Baby Rose nasturtium features compact growth of dark green leaves that are interspersed with sharply bright, rose-coloured flowers. The plants form small mounds with some cascading, so they're lovely in containers and raised beds. 
                The edible flowers come all summer long, particularly if spent flowers are removed. 
                Baby Rose was a 2019 All Americas Selections winner. ''',
    "Tulip": ''' The Triumph series of tulips is bred for large flowers on stout stems and they all make wonderful cut flowers. Tulip Apricona has large, apricot-pink flowers and grows to 40cm (16") tall in full sun to partial shade. The plants are hardy to Zone 3 and look amazing in mass plantings. Plant some extras to enjoy indoors. ''',
    "Sunflower": ''' Eriophyllum lanatum. Height to 30-60cm (12-24"). Also known as Oregon Sunshine. This native Common Woolly Sunflower is not a real sunflower, but blooms from May to August with intensely yellow 5cm (2") wide flowers that rise above silvery grey, woolly foliage. 
                It prefers full sun, but will bloom in partial shade. Common Woolly Sunflowers work well in containers, in the border, and in alpine rock gardens. Their spread is very gradual, and they are quite ornamental at all times of the year. 
                This plant is very attractive to pollinators and beneficial insects, so it deserves a place in every organic garden. Hardy to Zone 5.''',
    "Daisy": ''' Ismelia carinata. This highly variable Chrysanthemum is an annual that is native to North Africa. Also known as Tricolor Daisies, Painted Daisies add a colourful splash to nearly any garden setting. They can be grown in patio containers and thrive in full sun. 
                They look amazing in mass plantings. The petals range from bright white to deep crimson and are always banded by concentric circles of alternate colours as a guide to passing pollinators. The plants don't usually grow more than 45cm (18") tall. ''',
    "Marigold": ''' Tagetes patula. Brocade Marigold seeds produce brilliant 5cm (2") wide flowers in gold to mahogany atop 30-38cm (12-15") plants. This is a medium height marigold that works well in large containers. Grow in full sun and deadhead regularly to enjoy flowers from May to heavy frost. 
                The plants are drought resistant, so a good candidate for xeriscaping. The flower petals are edible, and can be dried and ground to use as a replacement for saffron. The essential oils of this marigold have apparent anti-fungal properties, and have been used to fight fungal infections on plants. 
                Brocade is a cultivar of T. patula, which is native to the highlands of central Mexico. It's a very easy flower to grow from seed. ''',
    "Poppy": ''' Papaver rhoeas. Sow heirloom Flanders poppy seeds for bright red summer colour in nearly any soil. Flanders poppies are quite drought tolerant, so they are useful in xeriscaping schemes. They self sow fairly reliably without ever becoming weedy. 
                It's a good choice for any areas where grasses are allowed to grow tall in summer, with the poppies growing to around 60cm (24") tall. Gather the dried seed heads in late summer for decorative dried flower arrangements. Plants produce abundant tiny seeds that are very easy to gather and give as gifts. 
                This species is mildly toxic to grazing animals, but its acrid taste puts most animals off anyway. So it is a very useful deer resistant variety that looks spectacular when planted in large areas.''',
}